name: Deploy to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_BASE: https://www.soupspoon.kr/api/v1
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}

      # Frontend-CICD-Manager IAM 사용자의 자격 증명으로 S3 접근
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Clear S3 bucket
        run: |
          aws s3 rm s3://www.soupspoon.kr --recursive

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://www.soupspoon.kr --delete

      - name: Notify Mattermost on Success
        if: success()
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          method: "POST"
          customHeaders: |
            Content-Type: application/json
          data: |
            {
              "text": ":white_check_mark: 배포 성공 - `${{ github.repository }}` 브랜치 `${{ github.ref_name }}`\n- 커밋: ${{ github.event.head_commit.message }}\n- 커밋터: ${{ github.event.head_commit.author.name }}"
            }
      - name: Notify Mattermost on Failure
        if: failure()
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          method: "POST"
          customHeaders: |
            Content-Type: application/json
          data: |
            {
              "text": ":fire: 배포 실패 - `${{ github.repository }}` 브랜치 `${{ github.ref_name }}`\n- 커밋: ${{ github.event.head_commit.message }}\n- 커밋터: ${{ github.event.head_commit.author.name }}"
            }
